### ISSUE TITLE
Crazy growth of resque-retry keys

### ISSUE THREAD

**Issue by pedro-brentan** [lantins/resque-retry#111]
Maybe related to https://github.com/lantins/resque-retry/issues/10, but in my case I can't figure out what causes the issue.

This is the situation of my keys:

irb(main):001:0> Resque.count_all_scheduled_jobs
=> 53094
irb(main):002:0> Resque.redis.keys("resque-retry:*").count
=> 829443

![screenshot from 2014-08-28 14 33 11](https://cloud.githubusercontent.com/assets/7505314/4082930/6984eada-2ef6-11e4-9cda-6103116f4bfd.png)

I would expect, in the worst case, these numbers to be equal, never retry > all_jobs. I've already checked and the distribution of keys between my jobs is equivalent to the proportion of execution of each job.

Any idea?

**Comment by keshav-bia** [comment]
@pedro-brentan , we had a similar issue and it turned out to be on our side where one of the resque hooks was unintentionally modifying the args.  This would cause the keys in resque-retry not to be deleted because the key name is calculated by hashing the args and so in before hook it would have one value but in after hook a different one and therefore not being able to delete it.

**Comment by mindware** [comment]
@pedro-brentan were you able to reproduce this in staging?

@lantins Does Expire Retry Counters From Redis work with the backoff_strategy?

**Comment by pedro-brentan** [comment]
Nope, @mindware, but we are not facing this growth anymore, still have some "lost" keys, but not at the same rate as before.

**Comment by mindware** [comment]
@lantins Any thoughts on the question?

**Comment by pedro-brentan** [comment]
I forgot mentioning we could mitigate this problem using expiration time.

**Comment by jzaleski** [comment]
@mindware in theory it should work as expected w/ the `backoff_strategy` as long as you're not doing anything funny w/ the `before_perform_retry` hook. To [better] inform our future selves perhaps you could try writing a test-case to verify it?
