### ISSUE TITLE
retry_delay being set results in no retry

### ISSUE THREAD

**Issue by Cervenka** [lantins/resque-retry#113]
Hi,
I tried using following parameters:
@retry_limit = 3
@retry_delay = 5

No retries are being run in that case.
If I do not set @retry_delay the retries are executed as expected.

I also tried using the default exponential backoff example. Any value higher than 0 results in no retries to be executed.

So any delay causes no retries to be executed.

Did I misconfigure something? Thank you.

**Comment by anujbiyani** [comment]
+1

setting `@retry_delay = 0` works, but setting it to something greater than 0 resulted in no retries.

**Comment by julienXX** [comment]
I can see that too.

**Comment by jzaleski** [comment]
It looks like you may have stumbled across a bug/regression @Cervenka! If you guys (@anujbiyani & @julienXX included) want to take a stab at writing a failing test-case and submit a pull-request for a fix I will help you to get it merged. Thanks guys!

**Comment by julienXX** [comment]
Will try to submit something :)

**Comment by jzaleski** [comment]
Sounds great! Thank you

**Comment by mindware** [comment]
Any progress on this?

**Comment by cbelsole** [comment]
I am still seeing this error.

**Comment by jzaleski** [comment]
Can you please provide the steps to reproduce?
