### ISSUE TITLE
Resque-scheduler 4.0

### ISSUE THREAD

**Issue by eapache** [lantins/resque-retry#115]
Resque-scheduler gem just released version 4.0: https://github.com/resque/resque-scheduler/blob/master/HISTORY.md

I don't think they changed the API much (if at all) so I *think* resque-retry is still compatible, but right now it's locked at `~> 3.0` so I'm not sure.

**Comment by eapache** [comment]
ping... will there be a release?

**Comment by lantins** [comment]
Sorry, let this one slip guys!
Will sort it out tonight :)

L

**Comment by jzaleski** [comment]
Thanks Luke!

**Comment by lantins** [comment]
v1.4.0 has been pushed
