### ISSUE TITLE
Resque 2.0 compatibility?

### ISSUE THREAD

**Issue by charliedrage** [lantins/resque-retry#116]
Has there been any progress on Resque >v2.0 compatibility?

**Comment by jzaleski** [comment]
Correct me if I'm wrong Luke, but I believe our intention was to wait until
Resque 2.0 was formally released (not release-candidate status) and then
apply any necessary changes. From our initial investigations we found that
the necessary changes *should* be relatively minimal to `resque-retry`

**Comment by charliedrage** [comment]
You're right, I just realized that it hasn't been "officially" released yet. Damn you github.

Once it's released I'll update this issue again, by then I'll have more knowledge of resque so I can help out.

**Comment by ygnessin** [comment]
@cdrage @jzaleski Resque 2.0 has been officially released now. Is there any intention of supporting it?
