### ISSUE TITLE
Retry with changed paramaters

### ISSUE THREAD

**Issue by zwarburg** [lantins/resque-retry#117]
I am trying to find a way to retry sending an email with different parameters. 

I am working on an application that relies very heavily on mailers. As such when the mailers stop working due to an issue with the services, we currently manually go in and change to use the secondary provider. 

In my **mailer_config.rb** I have:

    MAIL_PROVIDER_PRIMARY   = :ses
    MAIL_PROVIDER_SECONDARY = :sendgrid
    
    SMTP_SETTINGS = {
      :ses => {
        :address => MAILER_CONF[Rails.env]["ses"]["address"],
        ......
      },
      :sendgrid => {
        :address => MAILER_CONF[Rails.env]["sendgrid"]["address"],
    	....
      }
    }
    ActionMailer::Base.smtp_settings = SMTP_SETTINGS[MAIL_PROVIDER_PRIMARY]

When enough errors are triggered, we currently run a script that goes in and manually changes the last line to use `MAIL_PROVIDER_SECONDARY`. 

What I would like to do is as part of `resque_mailer.rb` be able to trigger this change automatically on a case by case basis. So, for example, if I try to send an email and it generates a `Net::SMTPAuthenticationError`, I would like to retry with `MAIL_PROVIDER_SECONDARY`. 

**rescue_mailer.rb**:

    Resque::Mailer.error_handler = lambda { |mailer, message, error, action, args|
      if error.is_a?(Net::SMTPAuthenticationError) && 'We are using MAIL_PROVIDER_PRIMARY'
      	#retry using ActionMailer::Base.smtp_settings = SMTP_SETTINGS[MAIL_PROVIDER_SECONDARY]
      else
        raise error
      end
    }

I know that I can use this gem to retry sending the email, but is there any way to tell it to rety with different parameters?

**Comment by jzaleski** [comment]
Yes @zwarburg there is.

See here:

https://github.com/lantins/resque-retry/blob/master/lib/resque/plugins/retry.rb#L157

Please let us know if you have any additional questions.

**Comment by lantins** [comment]
@jzaleski Always appreciated :+1:
