### ISSUE TITLE
Does resque-retry work with ruby minitest ?

### ISSUE THREAD

**Issue by leo-altiscale** [lantins/resque-retry#118]
Hi 

  I have a bunch of ruby selenium frontend test, I am using mintest to kick off all the test suite and would love to have some smart test re-try mechanism, I am wondering if resque-retry work with minitest?

  I have followed readme and tried it on my ruby tests, seems the retry doesn't work me.

Thx, any help is appreciated 
Leo

**Comment by leo-altiscale** [comment]
When I run cmd below, I got the error stack trace. it says "Error connecting to Redis on 127.0.0.1:6379", anything that I did wrong possibly
$QUEUE=* rake resque:work



WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
rake aborted!
Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis.rb:789:in `block in get'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-3.2.1/lib/redis.rb:788:in `get'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:290:in `method_missing'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/resque-1.25.2/lib/resque/worker.rb:617:in `job'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/resque-1.25.2/lib/resque/worker.rb:546:in `unregister_worker'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/resque-1.25.2/lib/resque/worker.rb:215:in `rescue in work'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/resque-1.25.2/lib/resque/worker.rb:162:in `work'
/Users/leoqiu/.rvm/gems/ruby-2.1.5/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
Tasks: TOP => resque:work
(See full trace by running task with --trace)

**Comment by jzaleski** [comment]
Hi @leo-altiscale is there something `resque` (https://github.com/resque/resque) specific you are looking to test because that is the only scenario in which `resque-retry` will help.

From your earlier comments/questions I don't think `resque-retry` is what you're looking for. You could probably benefit from something like `retryable` (https://github.com/nfedyashev/retryable).

**Comment by leo-altiscale** [comment]
thx so much, I will look into it

**Comment by jzaleski** [comment]
@leo-altiscale any objection to me closing this issue out?

**Comment by leo-altiscale** [comment]
no, thx so much for you hint, plz go ahead and close this :+1:
