### ISSUE TITLE
Exponential backoff not working in production

### ISSUE THREAD

**Issue by mindware** [lantins/resque-retry#119]
Hello @lantins and all,

I've noticed exponential backoff works great on development, but it's not working properly in production. Jobs are retried immediately, and then go directly to the retry queue but are not retried more than twice. Our exponential backoff strategy includes multiple retries, so it boggles the mind why it's not retrying more.

If we do a manual retry through the resque-web interface, it is processed properly.

Gemfile.lock looks like this:

GEM
  remote: https://rubygems.org/
  specs:
    aasm (3.2.1)
    dotenv (2.0.1)
    erubis (2.7.0)
    foreman (0.78.0)
      thor (~> 0.19.1)
    htmlentities (4.3.3)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.5)
    mono_logger (1.1.0)
    multi_json (1.11.0)
    netrc (0.7.9)
    rack (1.6.0)
    rack-protection (1.5.3)
      rack
    rake (10.4.2)
    redis (3.2.1)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    resque (1.25.2)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.3)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    resque-retry (1.4.0)
      resque (~> 1.25)
      resque-scheduler (~> 4.0)
    resque-scheduler (4.0.0)
      mono_logger (~> 1.0)
      redis (~> 3.0)
      resque (~> 1.25)
      rufus-scheduler (~> 3.0)
    rest_client (1.8.3)
      netrc (~> 0.7.7)
    rufus-scheduler (3.1.1)
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    thor (0.19.1)
    tilt (2.0.1)
    vegas (0.1.11)
      rack (>= 1.0.0)

PLATFORMS
  ruby

DEPENDENCIES
  aasm (~> 3.2.1)
  dotenv (~> 2.0.1)
  erubis (~> 2.7.0)
  foreman (~> 0.78.0)
  htmlentities (~> 4.3.3)
  mail (~> 2.6.3)
  rake (~> 10.4.2)
  redis (~> 3.2.1)
  resque (~> 1.25.2)
  resque-retry (~> 1.4.0)
  resque-scheduler (~> 4.0.0)
  rest_client (~> 1.8.3)

We require:
require 'resque'
require 'resque-scheduler'
require 'resque-retry'

Also:
require 'resque/tasks'
require 'resque/scheduler/tasks'
require 'resque/failure/redis'

Resque is also configured like this:
# require modules
Resque::Failure::MultipleWithRetrySuppression.classes = [Resque::Failure::Redis]
Resque::Failure.backend = Resque::Failure::MultipleWithRetrySuppression

We have a base worker, which is inherited by all other workers. It has the following:    
extend Resque::Plugins::ExponentialBackoff

Base worker uses this as its backoff strategy:
      @backoff_strategy = [10, 60, 300, 600, 3600, 10800, 21600, 43200, 86400,
                           97200, 108000, 140400, 172800, 183600, 194400, 216000,
                           259200, 302400, 345600, 388800, 432000, 475200, 518400,
                           561600, 604800, 648000,
                           691200, 777600, 864000, 950400, 1036800, 1123200,
                           1209600, 1814400, 2419200, 3024000, 3628800,
                           4233600, 4838400]

    @retry_delay_multiplicand_min = 1.0
    @retry_delay_multiplicand_max = 2.0

   @fatal_exceptions = [ItemNotFound, TransactionNotFound,
                           MissingTransactionId, IncorrectEmailParameters]

Any thoughts?

**Comment by mindware** [comment]
ping

**Comment by lantins** [comment]
It's really difficult for us to debug an issue without the ability to reproduce it, or access to your servers Everything _should_ work, there may be something in your production environment that's causes this behaviour.

Please feel free to hit me back on this, we'll reopen and look into it.

**Comment by mindware** [comment]
I'm very interested in looking into it. Would love to provide you with additional information so we can work this through.

**Comment by lantins** [comment]
Okay, so my question would be, can you reproduce this issue outside of your software?

**Comment by lantins** [comment]
And also, in production, how 'reliable' is the failure? all the time? or sometimes?

**Comment by lantins** [comment]
Do all workers, inheriting from the base worker, exhibit the same behaviour?

**Comment by lantins** [comment]
Finally (for the moment :)) can you try and capture the failure with debug logging enabled? https://github.com/lantins/resque-retry#debug-plugin-logging

I understand, if its not easy for you to try that out in _production_

**Comment by mindware** [comment]
Hello, 

I'm going to be opening a window for this to ocurr, I will report back with the findings and information.

**Comment by lantins** [comment]
Thanks

**Comment by lantins** [comment]
What was the outcome @mindware ? :)
