### ISSUE TITLE
Not working well with Exception-Notifier + Rake extension

### ISSUE THREAD

**Issue by lichtamberg** [lantins/resque-retry#120]
I use exception_notifier + rake extension (https://github.com/nikhaldi/exception_notification-rake) to get informed about failed resque tasks...

Now I installed resque-retry and I don't get exceptions anymore about my failed tasks...

Would be nice if someone could take a look at it, I also opened a ticket: https://github.com/nikhaldi/exception_notification-rake/issues/13

Thanks for the great work!

**Comment by jzaleski** [comment]
@lichtamberg to clarify, do you want to be notified when a `Task` fails fatally or each time a `Job` fails and is retried? My gut is telling me that this would be a feature we will need to add (can you confirm @lantins?). That being said, I will gladly help with reviewing/discussing any modifications to `'resque-retry'` to support this integration.  Have you had a chance to look at the code for our gem, or even `'resque'` itself, to see if this is possible?

**Comment by lichtamberg** [comment]
Hi @jzaleski , 
thanks for the quick reply!

This is my usecase:

I manage payment processes with it: After a payment has been sucessfully processed, i forward the new balance to another webservice (webserver, shows the balance to the user) -> here comes resque/resque-retry into the game.

Usually the forward-processes should work fine.. no exceptions should occure..

But: if the other receiving webservice is down (server restart, power failure...) i would like to receive the exception notifications of the failing forwarding-process... (just to be up to date when something is wrong)...
And: I would like that these failed tasks should be retried after some seconds/minutes, because it's important for our customers to see their correct balance, so I wouldn't like to retry all the failed forwarding processes by hand (could be 10-1000 entries, depending on the failure-duration).

The https://github.com/nikhaldi/exception_notification-rake gem works fine already for rake tasks (so also for resque workers).. but it seems that resque-retry is catching the exceptions, so no exception-mail is triggered...

I didn't look through the code of resque/resque-retry, but i will when I have time..

**Comment by lantins** [comment]
This request, thats sent to the 'balance web service', is that done by the resque job? or a rake task? or both?!

If you want to receive an email when a job fails, you can do that with the existing hook methods in resque and resque-retry, you could possibly even call the appropriate `exception_notification-rake` gem code when it happens.

I'm not familiar with the `exception_notification-rake` gem... but it does seem strange to use a gem build for RAKE tasks with RESQUE jobs?

**Comment by lantins** [comment]
https://github.com/lantins/resque-exceptional

I've used resque-exceptional along with resque-retry without issue before, this isn't too different from wanting to send emails on failure.

My gut tells me trying to use exception_notification-rake for this job is the wrong call.
If its preventing resque-retry from working, the gem should not be loaded/used by your job code, and then you use some hooks to notify you the job has failed.

Also, as an alternative, I'd monitor the number of failed jobs over a period of time, and trigger an email if the rate/number exceeded a threshold, rather then being notified possibly +1000's of times on every failure, improving the signal/noise ratio.

**Comment by lichtamberg** [comment]
Hi @latins,

the current balance (received over the payment webservice) is forwarded to another webservice (via resque)..

Resque itself is processing the tasks via rake, so I don't understand completely what you mean?
exception_notification-rake is not preventig resuqe-retry from working, its the opposite..
Retry things work fine, but also if I didn't include any retry strategies, I don't get any exception notifications anymore via mail...

So it seems that resqure-retry is catching the exception and not raising it like normal - when I don't specify a retry strategy..

**Comment by lantins** [comment]
@lichtamberg It seems a little odd your resque job is running a rake task...

Can you show us a Resque job that illustrates how your using Rake + the `exception_notification-rake` gem?

I _think_ you will be better not trying to reuse `exception_notification-rake` within the Resque job, and you _probbably_ want either a Resque failure backend that will email you or use the Resque hooks to do the same thing.

It depends on how much information needs to be in that email, is it purely a 'oh shit something went wrong' or does it need to be smarter then that?

The resque-retry gem will indeed capture the exceptions, that's kinda part of its design, they are not re-raised, as such your `exception_notification-rake` code is never being called.

**Comment by lichtamberg** [comment]
@lantins Ahh, now I get your point..

No no, I just ment that I start the resque workers by rake - just like a normal resque setup... My jobs are normal jobs like mentioned in the readme... Inside the jobs there are no rake tasks executed..

My whole point is, usually when a resque-worker instance is crashing (due to an exception) it sent me an exception mail.. After using resque-retry I don't get any exceptionmails at all..
I just would like to add an option for either one of the following usecases:

1) set an option for resque-worker WITHOUT retry strategy, to trigger the exception + exception mail
2) set an option for resque-worker WITH retry strategy, to send an exception mail like normal + retry it afterwards with the provided strategy..

Hope I described it now better? Sorry, english is not my mother language..

**Comment by lichtamberg** [comment]
Sorry @lantins , I also have to bring again some more light into this issue:

The exceptions are only NOT triggered when using following code

```
Resque::Failure::MultipleWithRetrySuppression.classes = [Resque::Failure::Redis]
Resque::Failure.backend = Resque::Failure::MultipleWithRetrySuppression
```

Without this, I get the exception notifications without problems! Sorry to confuse everybody, I just tried the "full solution" and thought it would be the same for the default failure backend... But it's not like this..

Under this circumstances I just have the following wish:

When I add the MultipleWithRetrySuppression handling and specify a retry limit (f.e. 5), I would like to get the exception triggered after the last retry failed (i mean when the 5th of the 5 specified retries failed at the end)..

**Comment by lichtamberg** [comment]
I found the issue.. I just have to add the ExceptionNotification::Resque failure backend to the MultipleWithRetrySuppression.classes... I created a pull request for this if you like?

Thanks for your help!

**Comment by lantins** [comment]
@lichtamberg Glad you got this sorted!
