### ISSUE TITLE
Missing tag for v1.4.0

### ISSUE THREAD

**Issue by leighmcculloch** [lantins/resque-retry#121]
v1.4.0 while on rubygems, doesn't have a tag on this repository. Could a tag be added please? Stumbled on this recently when I needed to look at the source code for the version of the gem I was using.

**Comment by lantins** [comment]
Well spotted!

Done.

**Comment by lantins** [comment]
https://github.com/lantins/resque-retry/releases/tag/v1.4.0

**Comment by leighmcculloch** [comment]
@lantins thanks!

**Comment by lantins** [comment]
@leighmcculloch Welcome :)
