### ISSUE TITLE
How to test the retry has been scheduled?

### ISSUE THREAD

**Issue by foohey** [lantins/resque-retry#125]
Hi!
I have some trouble to test that the retry has been scheduled.

The job :

```ruby
require "resque-retry"

class Coordinates < Resque::Job
  extend Resque::Plugins::Retry

  @queue            = :coordinates
  @retry_limit      = 5
  @retry_delay      = 1.day.to_i # Should be in seconds
  @retry_exceptions = [ Geocoder::OverQueryLimitError ]

  def self.perform( id, entered_by_user, schema )
    # ...
  end
```

The spec :

```ruby
it 'enqueue the job to be retried in 1 day' do
  allow( Coordinates ).to receive( :perform ) do |id, entered_by_user, schema|
    raise Geocoder::OverQueryLimitError
  end

  expect {
    Coordinates.perform( @address.id, @address.entered_by_user, Apartment::Tenant.current  )
  }.to raise_error Geocoder::OverQueryLimitError

  expect(Coordinates).to have_scheduled(
    @address.id,
    @address.entered_by_user,
    Apartment::Tenant.current
  ).in(1.day)
end
```

But nothing seems to be scheduled :(

**Comment by lantins** [comment]
I suggest you don't try to do this, making sure the gem works as advertised is covered by the projects test suite, you don't need to repeat these tests in your tests. It would be like testing the internals of Active Record.

If you _really_ want to do it, for some kind of integration test, take a look at our test suite and see what we're doing, mostly checking that the expected key was placed in Redis.

**Comment by foohey** [comment]
Ok so I'm finally done by using some of your helpers and creating a resque worker and enqueue the job, I don't know why I called `.perform` directly...

Sample: https://gist.github.com/foohey/b40f9ed4fa4941bf78c5

But I do not agree with you on the fact to not test again because the library already do it.
What happen if I upgrade ruby/rails/resque and so on, and/or you don't maintain anymore the gem ?
Our app is so big that we can't take risks, especially with background jobs that are hard to debug / ensure they are working.

This cost nothing to test that and it add better coverage :)

**Comment by jzaleski** [comment]
Hi @foohey I think @lantins was saying was that you can safely assume that the tests we have written are covering issues we have identified and test-cases we felt were important while developing the gem. In my opinion, for unit-testing, you should only test functionality you add. If you have more complex test-cases and want to test libraries you monkey-patch or extend then it may make sense to write unit-tests.

For your other point, if we stop maintaining the gem, this is not something we're intending on doing any time soon, then you may find yourself in a bind. However, that being said, we also won't be releasing any new versions of the gem in which case the version you are on at that time will probably already be stable/battle-tested. If you are relying on specific behaviors of `resque-retry` for your day to day operations that's great! But also disconcerting and possibly indicative of a larger problem in your system. Either way, we're both happy to help in any way we can while we are maintaining them gem and wish you the best of luck in your continued usage.

Closing..
