### ISSUE TITLE
UI crashes if a job that is not defined in Ruby is viewed

### ISSUE THREAD

**Issue by evantahler** [lantins/resque-retry#130]
There are a number of other packages in the Resque ecosystem (node, php, etc), and not just Ruby.  I'm working on a node implementation of the data structures and logic found in this package.

Your UI addons assume that the job classes have been loaded into the server which is running the resque-web interface.  Even in Ruby, you might have a seperate sinatra app for the UI which doens't load any of the job classes.  Calling [`constantize`](https://github.com/lantins/resque-retry/blob/master/lib/resque-retry/server.rb#L76-L78) fails if the job class is not present in Ruby's memory.

**Comment by jzaleski** [comment]
Thanks for the report @evantahler. I'd be happy to review/approve a pull-request addressing the issue if you submit one. Thanks!

**Comment by evantahler** [comment]
Sure thing.  Moving to #131
