### ISSUE TITLE
Does 'resque-retry' work for 'Redis::CannotConnectError' error

### ISSUE THREAD

**Issue by saraw0** [lantins/resque-retry#141]
Hi,
I use Resque with Redis and I have a lot of failures: "Redis::CannotConnectError: Timed out connecting to Redis on ..."

I want to use  resque-retry but I don't know if it will help. because I think that it fails before the perform method.

Will it solve my errors? or do you have another idea?

**Comment by lantins** [comment]
`resque-retry` helps with exceptions that happen during the execution of your job, we rely on the the Redis instance used for resque's queue being available to achieve this.

Does this happen when your workers connect to Redis to pull jobs? or is it something else within your application logic that uses Redis?

**Comment by saraw0** [comment]
This happen when resque workers connect to Redis to pull jobs. 
Copy here the exception from resque web console:
```
Exception
Redis::CannotConnectError
Error
Error connecting to Redis on localhost:6379 (ECONNREFUSED)
```
Do you have any idea how I can resolve it?
