### ISSUE TITLE
Does 'resque-retry' work for 'Redis::CannotConnectError' error

### ISSUE THREAD

**Issue by saraw0** [lantins/resque-retry#143]
Hi, I use Resque with Redis and I have a lot of failures: "Redis::CannotConnectError: Timed out connecting to Redis on ..."

When my resque workers connect to Redis to pull jobs I have this error:

```
Exception
Redis::CannotConnectError
Error
Error connecting to Redis on localhost:6379 (ECONNREFUSED)
```
Do you have any idea how I can resolve it?

**Comment by jzaleski** [comment]
Closing as "Won't Fix" -- seems to be a local environment issue. Please re-file a ticket if the issue persists
