### ISSUE TITLE
release  v1.5.1

### ISSUE THREAD

**Issue by michaelglass** [lantins/resque-retry#148]
Howdy, @lantins!

Can you grant @jzaleski (or other contributors) gem push access and/or release the 1.5.1 version?

🥇 Thank you for your delightful gem! 🥇

**Comment by michaelglass** [comment]
thank you!

**Comment by arturoherrero** [comment]
Can you push a new version of the gem to Rubygems, please? @lantins @jzaleski

**Comment by michaelglass** [comment]
happy to also volunteer as a maintainer if it helps

**Comment by jzaleski** [comment]
Unfortunately this is not a case of where throwing more people at the problem, or repetitive asking, will help Michael. 

Everything that can be done right now has been done. Unfortunately Luke just hasn't been available.

**Comment by michaelglass** [comment]
unrelated status update: recently emailed Luke

**Comment by michaelglass** [comment]
It's been about four months. @jzaleski would you be interested in asking RubyGems for push access?

**Comment by jzaleski** [comment]
`resque-retry@1.5.2` is now available on RubyGems (and I'm an _Owner_) so this shouldn't happen again.

```bash
> ~/src/resque-retry master gem push resque-retry-1.5.2.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: resque-retry (1.5.2)
```

Thanks for your patience!
