### ISSUE TITLE
Retry doesn't seem to work on 1.5.2

### ISSUE THREAD

**Issue by annapetry** [lantins/resque-retry#152]
Two of our projects have stopped retrying failed jobs in after updating to 1.5.2.

Perhaps this PR is the culprit: https://github.com/lantins/resque-retry/pull/137

**Comment by jzaleski** [comment]
`1.5.1` was never released, so it is possible. There wasn't much new in `1.5.2` outside of that.

Can you please provide more detail about the issue and why you think it could be related to https://github.com/lantins/resque-retry/pull/137 ?

(CC: @michaelglass)

**Comment by jzaleski** [comment]
Closing. If this issue is still being seen / recurs, please open a new issue here. Thanks
