### ISSUE TITLE
Undefined method requeue_queue when retrying failed queue

### ISSUE THREAD

**Issue by fcbr** [lantins/resque-retry#153]
Using `gem 'resque-retry', '~> 1.5.2'` with `Rails 4.2.10`:

We are getting this exception when attempting to retry all jobs for a particular queue --- the `Retry 'Q_failed' jobs` button on the `/resque/failed/Q_failed` URL:

```
2018-11-26 07:25:33 - NoMethodError - undefined method `requeue_queue' for Resque::Failure::MultipleWithRetrySuppression:Class:
	/.../vendor/bundle/ruby/2.4.0/gems/resque-1.27.4/lib/resque/failure.rb:104:in `requeue_queue'
```

Indeed, `resque` calls this method when attempting to retry a queue: https://github.com/resque/resque/blob/v1.27.4/lib/resque/failure.rb#L101-L105

Our `resque.rb` initializer is configured as such:

```
require 'resque/failure/redis_multi_queue'

Resque::Failure::MultipleWithRetrySuppression.classes = [Resque::Failure::RedisMultiQueue]
Resque::Failure.backend = Resque::Failure::MultipleWithRetrySuppression
```

**Comment by jzaleski** [comment]
I monkey-patched this into the `resque-retry` gem for now and opened a PR w/ `Resque` (https://github.com/resque/resque/pull/1659) to address the issue upstream.
