### ISSUE TITLE
Support for resque 2.0

### ISSUE THREAD

**Issue by ygnessin** [lantins/resque-retry#154]
Is there any intention for this gem to support resque 2.0 or higher? I see that this was brought up over 3 years ago in #116, but as of a month ago [2.0.0 has finally been officially released](https://github.com/resque/resque/releases/tag/v2.0.0).

Thanks for the great library!

**Comment by nimashariatian** [comment]
indeed this would be really great

**Comment by jzaleski** [comment]
I **have not** been using `resque` for nearly 5 years at this point, but regardless, I've been helping maintain this _gem_.

I don't know that I'm up for what it would take to upgrade this for compatibility however I'd be happy to help move PRs along if anyone wants to work on this.

**Comment by nimashariatian** [comment]
@jzaleski I'm curious to know what have you been using as a replacement? and any particular reason?

**Comment by jzaleski** [comment]
The main reason is that I have been working w/ other technologies :-)

While I do currently oversee multiple public facing `ruby` projects, we haven't found the need for a _job_ processing framework (yet).

I would still consider `resque` if the need ever did arise, however.

**Comment by ygnessin** [comment]
@jzaleski Thanks for the response. If this gem isn't being actively maintained anymore, would you accept a PR with an update to the README to discourage potential first-time users from integrating it?

**Comment by nimashariatian** [comment]
what are some alternatives, good forks of this ? 
anyone? ..

**Comment by jzaleski** [comment]
I think you misunderstood. This gem is being maintained. However, adding support for resque 2.0 is not a maintenance request. If you either of you would like to take it on and give back to the open-source community we'd be happy to assist in reviewing / merging any submitted pull-requests.

**Comment by nimashariatian** [comment]
thanks for clarifying, i think were was a confusion in the thread

**Comment by jeremy** [comment]
@peret, resque-scheduler 4.4.0 is now released with Resque 2 support, so you're free to upgrade resque-retry as well.

**Comment by jzaleski** [comment]
Alrighty! It's out there: https://rubygems.org/gems/resque-retry/versions/1.6.0
