### ISSUE TITLE
Test suite seems to contain order-dependent test cases

### ISSUE THREAD

**Issue by peret** [lantins/resque-retry#157]
Running the test suite using `rake test TESTOPTS="--seed=10451"` will cause two test cases to fail: RetryCallbacksTest#test_try_again_callback_exception and RetryCallbacksTest#test_give_up_callback_exception.

Running it using the seed 39172 (`rake test TESTOPTS="--seed=39172"`) causes seven test cases to fail.
<img width="928" alt="resque-retry_—_peter_Peters-MBP_—_-zsh_—_Solarized_Dark_Yosemite_—_211×55" src="https://user-images.githubusercontent.com/617977/56460734-c9edbd80-63a7-11e9-92ed-426f57c8a9b1.png">

Other seed values work though, e.g. 6729, which leads me to believe that these test cases implicitly depend on test execution order.

**Comment by jzaleski** [comment]
This was resolved w/ https://github.com/lantins/resque-retry/commit/4d82c449d3c07da5e40dfa169aa46630a4b0d4bb#diff-dba173159ef6c0cec751762c5317295dL3 -- the duplicate class name was causing issues w/ the `setup` method:

```bash
$SOURCE_DIRECTORY/resque-retry/test/retry_test.rb:6: warning: method redefined; discarding old setup                                                                                                          
$SOURCE_DIRECTORY/resque-retry/test/retry_exception_delay_test.rb:4: warning: previous definition of setup was here
```

Closing
