### ISSUE TITLE
 got #<NoMethodError: undefined method `<=' for nil:NilClass> with backtrace:

### ISSUE THREAD

**Issue by palexvs** [lantins/resque-retry#158]
I get an exception:
```
got #<NoMethodError: undefined method `<=' for nil:NilClass> with backtrace:
 # .../resque-retry/lib/resque/plugins/retry.rb:135:in `block in retry_delay'
 # .../resque-retry/lib/resque/plugins/retry.rb:135:in `select'
 # .../resque-retry/lib/resque/plugins/retry.rb:135:in `retry_delay'
 # .../resque-retry/lib/resque/plugins/retry.rb:458:in `before_perform_retry'
```

when I try to use `@retry_exceptions = {..}` with `@expire_retry_key_after = ..`

It happens because:
```
      def before_perform_retry(*args)
        ...
        if expire_retry_key_after
          log_message "updating expiration for retry key: #{retry_key}", args
          Resque.redis.expire(retry_key, retry_delay + expire_retry_key_after)
                                         ^^^^^^^^^^^
        end
      end
```
calls `retry_delay` without passing `exception_class`:
```
      def retry_delay(exception_class = nil)
        if @retry_exceptions.is_a?(Hash)
          delay = @retry_exceptions[exception_class] ||= begin
            relevant_definitions = @retry_exceptions.select { |ex| exception_class <= ex }
                                                                   ^^^^ nil ^^^^
           ...
          end
        end
      end
```

**Comment by palexvs** [comment]
I have applied a durty hack in my fork:
```
          Resque.redis.expire(retry_key, retry_delay_max + expire_retry_key_after)
        end
      end

      def retry_delay_max
        if @retry_exceptions.is_a?(Hash)
          @retry_exceptions.values.flatten.max
        else
          0
        end
      end
```

**Comment by jzaleski** [comment]
I was unable to reproduce this issue on `ruby-2.6.2` however the change still seemed simple enough so I put in an explicit check for `exception_class` being `nil` in commit: https://github.com/lantins/resque-retry/commit/d893957e050fa3c3fd5a49c8721d2692dbb48db1 release: https://github.com/lantins/resque-retry/releases/tag/v1.7.1 -- provided there are no issues in CI this will be on _RubyGems_ shortly.

Just so I know, which version of the `gem` and `ruby` were you running?

**Comment by palexvs** [comment]
Do you have a test where both settings `@expire_retry_key_after` and `@retry_exceptions = {..}` are defined?

**Comment by jzaleski** [comment]
The only thing that is required to trigger the code-path was added in the commit I mentioned above.

An `exception_class` of `nil` does not result in an error on any of the versions we support (ruby-2.3+ and jruby-9.1), before or after the fix.

Regardless, the commit I mentioned above will address your issue and will not disrupt the previous behavior.

Thanks

**Comment by palexvs** [comment]
Hi @jzaleski 
I created a test that shows `@expire_retry_key_after` and `@retry_exceptions = {..}` are still broken https://github.com/lantins/resque-retry/pull/159

If I set:
```
@expire_retry_key_after = 10
@retry_exceptions = { StandardError => 7, .. }
```

I expect `before_perform_retry` set expiration 17 sec for `retry_key` (https://github.com/lantins/resque-retry/blob/master/lib/resque/plugins/retry.rb#L459). But it calls `retry_delay` with no parameter and as a result, it always returns `0`. And we get expiration equal to `10`

**Comment by jzaleski** [comment]
This should be [fully] addressed in https://github.com/lantins/resque-retry/releases/tag/v1.7.2
