### ISSUE TITLE
ArgumentError: given 1, expected 0 for Resque::Plugins::ExponentialBackoff.retry_delay

### ISSUE THREAD

**Issue by oehlschl** [lantins/resque-retry#160]
After upgrading from 1.7.1 to 1.7.2, we started getting the following exception:

```
ArgumentError: wrong number of arguments (given 1, expected 0)
# .../resque-retry-652fa52a94b5/lib/resque/plugins/exponential_backoff.rb:86:in `retry_delay'
# .../resque-retry-652fa52a94b5/lib/resque/plugins/retry.rb:460:in `before_perform_retry'
```

It looks like it's due to the addition of the exception_class arg here: https://github.com/lantins/resque-retry/compare/v1.7.1...v1.7.2#diff-b502cc9827d813a7428fd95aa26a7f33R460

This argument is present in the signature of `Resque::Plugins::Retry.retry_delay`, but not in `Resque::Plugins::ExponentialBackoff.retry_delay`:
https://github.com/lantins/resque-retry/blob/master/lib/resque/plugins/exponential_backoff.rb#L86

I'll open up a PR to add it for parity and attempt a spec as well.

**Comment by oehlschl** [comment]
It's clearly not super urgent since no one else has filed this, but since it's a bugfix, do you mind taking a look @jzaleski? Would be nice to get back on the main line from our fork whenever we can.

Thanks in advance!

**Comment by Nullset14** [comment]
We are still seeing this issue in the latest version. Is https://github.com/lantins/resque-retry/pull/161 waiting for a re-review?

**Comment by jzaleski** [comment]
> We are still seeing this issue in the latest version. Is #161 waiting for a re-review?

Just approved / merged the PR -- please re-test on the head git-revision, I will push a new gem-version as soon as possible.

**Comment by jzaleski** [comment]
Released v1.7.4: https://github.com/lantins/resque-retry/commit/5d9dd7026b26fca8a00cd3cfb3639c1e68287324 to _rubygems_

**Comment by Nullset14** [comment]
We no longer see the exceptions with the new changes. Thank you for the quick turnaround.

**Comment by lantins** [comment]
@jzaleski 👏
