### ISSUE TITLE
Multiple failure backend not working

### ISSUE THREAD

**Issue by parikshit223933** [lantins/resque-retry#172]
The documentation mentions that 
```
If a job fails, but can and will retry, the failure details wont be logged in the Redis failed queue (visible via resque-web).
```

But these are getting enqueued in the failed queue on each and every failure.

I have the following in my config/application.rb

```
require 'resque-sentry'
require 'resque-retry'
require 'resque/failure/redis'

Resque::Failure::Sentry.logger = 'resque'
Resque::Failure::MultipleWithRetrySuppression.classes = [Resque::Failure::Redis, Resque::Failure::Sentry]
Resque::Failure.backend = Resque::Failure::MultipleWithRetrySuppression
```

Following is my worker code.

```
require 'resque-retry'

module Workers
  class Testing
    extend Resque::Plugins::JobStats
    extend Resque::Plugins::Retry

    @queue = :low
    @retry_delay = 1
    @retry_limit = 3

    def self.perform(_a)
      if rand(2) == 1
        puts "FAILED #{Time.current}"
        raise 'Some exception'
      else
        puts "SUCCEEDED #{Time.current}"
        return
      end
    end
  end
end
```

I am using resque version 2.0.0 and resque-retry version 1.7.6, resque-scheduler version 4.4.0

**Comment by jzaleski** [comment]
Hi @parikshit223933 -- it has been years since I've used `resque` and / or `resque-retry` for any project I've worked on, but I will certainly help you with this if I can.

Do you think you could convert the snippet above into a failing test-case for this gem? That will make troubleshooting / resolving this issue far easier for all of us.

**Comment by parikshit223933** [comment]
Hi, I have found the issue.
We are using resque 2.0.0 which uses redis namespace 1.6.0 internally.
[This line](https://github.com/lantins/resque-retry/blob/f53624e3961a0f33493a0a9f37b78f79ff573438/lib/resque/failure/multiple_with_retry_suppression.rb#L35) is causing the issue. Inside the function `retrying?` -> `redis_key_exists?`
[This](https://github.com/lantins/resque-retry/blob/f53624e3961a0f33493a0a9f37b78f79ff573438/lib/resque/failure/multiple_with_retry_suppression.rb#L146) line is returning true
```ruby
Resque.redis.respond_to?(:exists?)
```
And hence it is trying to fetch the corresponding redis key
via 
```
Resque.redis.exists?(key)
```

Resque.redis gives an object of Resque::DataStore which has an instance variable @redis which is an object of redis-namespace.

My key is `resque-retry:Workers::Testing` which is stored in redis as `resque:resque-retry:Workers::Testing`, but because of [this issue (blind passthrough)](https://github.com/resque/redis-namespace#blind-passthrough) in redis-namespace, exists? is being sent directly to redis from where, redis is saying that `resque-retry:Workers::Testing` key does not exist and hence returning false. whereas, had this blind passthrough issue not been there, redis-namespace would have checked for `resque:resque-retry:Workers::Testing` key instead and the result would have been correct i.e. `true`.
