### ISSUE TITLE
gzip stack trace

### ISSUE THREAD

**Issue by nirvdrum** [lantins/resque-retry#43]
resque-retry stores a copy of the stacktrace on all failures it's retrying.  In hindsight, this makes a lot of sense.  But I've also watched it take down two different clusters.  In both cases, something went awry, exceptions piled up, redis filled up with keys from resque-retry, redis ran out of memory, redis restarted loading an old DB, those same jobs started processing again, and the whole process was repeated.

For a small hit in CPU, the stacktraces can be compressed pretty well using zlib and conserve RAM for redis.

**Comment by nirvdrum** [comment]
Well, this was a blast from the past.  Thanks for closing :-)

**Comment by lantins** [comment]
Thanks for your contribution :-)
